import stat

USER_AMOUNT = 5
MIN_USER_PASSWD_LEN = 4
MIN_ADMIN_PASSWD_LEN = 2 * MIN_USER_PASSWD_LEN
DISK_NAME = 'disk'
ALL_SUBDISKS = ['A', 'B', 'C', 'D', 'E', 'admin', 'admin/keys']
PERMITTED_SUBDISKS = ['A', 'E']
USER_PERMISSIONS = stat.S_IRWXO | stat.S_IRWXG
OS_USERNAME = 'file_system_user_account'
SESSION_TIMEOUT_SEC = 360
PASSWD_LIFETIME_DAYS = 3
REGISTRATION_JOURNAL = f'{DISK_NAME}/admin/journal.txt'
QUESTIONS_STORAGE = f'{DISK_NAME}/admin/ask.txt'
ERRORS_COUNTER = f'{DISK_NAME}/admin/err_count.txt'
OPERATIVE_JOURNAL = f'{DISK_NAME}/admin/operative_journal.txt'
REPORT_PATH = f'{DISK_NAME}/admin/report.txt'
QUESTIONS_PER_USER = 3
MISTAKES_CRITICAL_N = 4
QUESTIONS_INTERVAL_MIN = 5
REPORT_INTERVAL_DAYS = 3
KEY_LENGTH = 56
USER_KEYS_PATH = f'{DISK_NAME}/admin/keys'
KEYS_LIFETIME_DAYS = 5
