import stat

USER_AMOUNT = 5
MIN_USER_PASSWD_LEN = 3
MIN_ADMIN_PASSWD_LEN = 2 * MIN_USER_PASSWD_LEN
DISK_NAME = 'disk'
ALL_SUBDISKS = ['A', 'B', 'C', 'D', 'E', 'admin']
PERMITTED_SUBDISKS = ['A', 'E']
USER_PERMISSIONS = stat.S_IRWXO | stat.S_IRWXG
OS_USERNAME = 'file_system_user_account'
SESSION_TIMEOUT_SEC = 360
PASSWD_LIFETIME_DAYS = 3
REGISTRATION_JOURNAL = f'{DISK_NAME}/admin/journal.txt'
QUESTIONS_STORAGE = f'{DISK_NAME}/admin/ask.txt'
ERRORS_COUNTER = f'{DISK_NAME}/admin/err_count.txt'
QUESTIONS_PER_USER = 3
MISTAKES_CRITICAL_N = 4
QUESTIONS_INTERVAL_MIN = 5
